/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.jhbot.db.tables.records;


import com.plumealerts.jhbot.db.tables.MinecraftWhitelist;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MinecraftWhitelistRecord extends UpdatableRecordImpl<MinecraftWhitelistRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>minecraft_whitelist.DISCORD_ID</code>.
     */
    public void setDiscordId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>minecraft_whitelist.DISCORD_ID</code>.
     */
    public String getDiscordId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>minecraft_whitelist.DISCORD_USERNAME</code>.
     */
    public void setDiscordUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>minecraft_whitelist.DISCORD_USERNAME</code>.
     */
    public String getDiscordUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>minecraft_whitelist.MINECRAFT_UUID</code>.
     */
    public void setMinecraftUuid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>minecraft_whitelist.MINECRAFT_UUID</code>.
     */
    public String getMinecraftUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>minecraft_whitelist.MINECRAFT_USERNAME</code>.
     */
    public void setMinecraftUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>minecraft_whitelist.MINECRAFT_USERNAME</code>.
     */
    public String getMinecraftUsername() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return MinecraftWhitelist.MINECRAFT_WHITELIST.DISCORD_ID;
    }

    @Override
    public Field<String> field2() {
        return MinecraftWhitelist.MINECRAFT_WHITELIST.DISCORD_USERNAME;
    }

    @Override
    public Field<String> field3() {
        return MinecraftWhitelist.MINECRAFT_WHITELIST.MINECRAFT_UUID;
    }

    @Override
    public Field<String> field4() {
        return MinecraftWhitelist.MINECRAFT_WHITELIST.MINECRAFT_USERNAME;
    }

    @Override
    public String component1() {
        return getDiscordId();
    }

    @Override
    public String component2() {
        return getDiscordUsername();
    }

    @Override
    public String component3() {
        return getMinecraftUuid();
    }

    @Override
    public String component4() {
        return getMinecraftUsername();
    }

    @Override
    public String value1() {
        return getDiscordId();
    }

    @Override
    public String value2() {
        return getDiscordUsername();
    }

    @Override
    public String value3() {
        return getMinecraftUuid();
    }

    @Override
    public String value4() {
        return getMinecraftUsername();
    }

    @Override
    public MinecraftWhitelistRecord value1(String value) {
        setDiscordId(value);
        return this;
    }

    @Override
    public MinecraftWhitelistRecord value2(String value) {
        setDiscordUsername(value);
        return this;
    }

    @Override
    public MinecraftWhitelistRecord value3(String value) {
        setMinecraftUuid(value);
        return this;
    }

    @Override
    public MinecraftWhitelistRecord value4(String value) {
        setMinecraftUsername(value);
        return this;
    }

    @Override
    public MinecraftWhitelistRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MinecraftWhitelistRecord
     */
    public MinecraftWhitelistRecord() {
        super(MinecraftWhitelist.MINECRAFT_WHITELIST);
    }

    /**
     * Create a detached, initialised MinecraftWhitelistRecord
     */
    public MinecraftWhitelistRecord(String discordId, String discordUsername, String minecraftUuid, String minecraftUsername) {
        super(MinecraftWhitelist.MINECRAFT_WHITELIST);

        setDiscordId(discordId);
        setDiscordUsername(discordUsername);
        setMinecraftUuid(minecraftUuid);
        setMinecraftUsername(minecraftUsername);
    }
}
