/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.jhbot.db;


import com.plumealerts.jhbot.db.tables.MinecraftWhitelist;
import com.plumealerts.jhbot.db.tables.records.MinecraftWhitelistRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MinecraftWhitelistRecord> PK_MINECRAFT_WHITELIST = Internal.createUniqueKey(MinecraftWhitelist.MINECRAFT_WHITELIST, DSL.name("pk_minecraft_whitelist"), new TableField[] { MinecraftWhitelist.MINECRAFT_WHITELIST.DISCORD_ID }, true);
}
