/*
 * This file is generated by jOOQ.
 */
package com.plumealerts.jhbot.db;


import com.plumealerts.jhbot.db.tables.MinecraftWhitelist;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>minecraft_whitelist</code>.
     */
    public static final MinecraftWhitelist MINECRAFT_WHITELIST = MinecraftWhitelist.MINECRAFT_WHITELIST;
}
